### ISSUE TITLE
Also need add Rating in Class MovieController.cs  

### ISSUE THREAD

**Issue by magrueso** [aspnet/Docs.es-es#30] opened 2019-03-08 19:41 UTC
For the new field function in all the projject you need modify   public async Task&lt;IActionResult&gt; Edit(int id, [Bind("Id,Title,ReleaseDate,Genre,Price,Rating")] Movie movie)

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: cca95f5e-0fe4-bbd2-fd23-13562e02f888
* Version Independent ID: c3fb9673-4da6-5eeb-08bb-6f8e7bc8e0c6
* Content: [Agregar un campo nuevo a una aplicación de ASP.NET Core MVC](https://docs.microsoft.com/es-es/aspnet/core/tutorials/first-mvc-app/new-field?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/new-field.md](https://github.com/aspnet/docs.es-es/blob/live/aspnetcore/tutorials/first-mvc-app/new-field.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment] 2019-03-08 20:23
Yes, that's in the tutorial. 
`[Bind("ID,Title,ReleaseDate,Genre,Price,Rating")]`

recommend you close this.

**Comment by CeciAc** [comment] 2019-03-11 12:21
Hello, @magrueso 

Your contribution is much appreciated. I see the issue is solved, but if you have further doubts, please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Closed by CeciAc** 2019-03-11 12:21 UTC
Labels: Product Feedback
